# Look at the flamegraph first

This SVG is generated from a **real folded capture**: `spur graph build --root ../ade-bench` (cold, embeddings off).

| | |
|---|---|
| Wall / user / sys | 6.75s / 4.72s / 1.36s (`/usr/bin/time -l`) |
| Mode | `Full` — 1,461 files, 12,237 nodes (python + markdown) |
| Sampler | `samply record --rate 4000` (macOS, no sudo) |
| Folded | `test/data/spur-ade-bench.folded` — 25,782 on-CPU samples, 2,289 unique stacks |
| SVG | `test/data/spur-ade-bench.svg` — written from that folded file |

Width is inclusive time; root at the bottom. Hover a frame for name + %.

A flamegraph is the right **picture**. It is the wrong **query surface** for a data-analyst performance investigation — that is why `quack_flamegraph` loads the same stacks into DuckDB.

In [9]:
"""Rebuild the SVG from the live folded file and display it."""
import subprocess
import sys
from pathlib import Path

from IPython.display import HTML, display


def repo_root() -> Path:
    here = Path.cwd().resolve()
    for p in [here, *here.parents]:
        if (p / "Cargo.toml").exists() and (p / "test" / "data" / "spur-ade-bench.folded").exists():
            return p
    raise FileNotFoundError(f"repo root not found from cwd={here}")


ROOT = repo_root()
FOLDED = ROOT / "test/data/spur-ade-bench.folded"
SVG = ROOT / "test/data/spur-ade-bench.svg"
SCRIPT = ROOT / "scripts/folded_to_svg.py"

r = subprocess.run(
    [sys.executable, str(SCRIPT), str(FOLDED), "-o", str(SVG),
     "--title", "spur graph build --root ../ade-bench (cold, no embeddings)"],
    check=True, capture_output=True, text=True,
)
print(r.stdout.strip())
display(HTML(
    "<div style='font-family:ui-sans-serif,system-ui,sans-serif;margin:0 0 8px 0'>"
    "<div style='font-size:13px;color:#444;margin:0 0 6px 0'>"
    "Live folded → SVG: <code>test/data/spur-ade-bench.folded</code> → "
    "<code>test/data/spur-ade-bench.svg</code>"
    "</div>"
    f"{SVG.read_text()}"
    "</div>"
))

samples 25782 stacks 2289 wrote /Volumes/Projects/Projects/quack-flamegraph/test/data/spur-ade-bench.svg

## Why a data analyst still needs `quack_flamegraph`

Hover the fat plateau through `extract_files` / `build_facts` (~74% coverage) and the hottest **leaf** `ts_parser_parse` (~9% exclusive). That is a useful first look. It is not a decision procedure.

On this live ade-bench capture the picture already misleads in the usual ways:

- The C parser leaf looks like “the bug”. Inclusive coverage says most stacks are inside `spur_graph::extract::tree_sitter::extract_files` (~74%), and Python re-export resolution is ~19% — a product path, not `ts_lex`.
- Widths overlap. You cannot ask “what is left if we skip re-export resolution?” without a `WHERE`.
- Exclusive vs coverage vs parent→child edges are different rankings. The SVG shows one of them (inclusive width).

| Question you actually have to answer | What the SVG gives you | What `quack_flamegraph` gives you |
|---|---|---|
| What % of *unique stacks* contain this frame? | A guessed width (inclusive, overlapping) | `flamegraph_coverage` — each stack counted once |
| Did a recursive name inflate the hotspot? | Easy to miss stacked same-name frames | Join coverage vs `flamegraph_inclusive` |
| What is the hottest *parent → child* edge? | Adjacency you squint at | `flamegraph_edges` |
| Hottest leaf vs product path? | Leaf name (`ts_parser_parse`, a C helper) | Coverage of `extract_files` / Python re-export |
| If we drop that path, what is left? | Record a new profile | `WHERE NOT list_contains(frames, …)` then re-chart |
| Do buckets sum to 100%? | No — widths overlap | Disjoint `CASE` over unique stacks |

Squinting at rectangles is how you **start**. Ranking a fix from a join is how you **stop guessing**.

The SQL + GGSQL cells below query **this** capture (`test/data/spur-ade-bench.folded` → `build/perf-demo/*.parquet`).

Loop (do not skip a step):

1. **Time** — 6.75s wall for this capture.
2. **Profile as tables** — `read_folded` → coverage / exclusive / edges.
3. **Quantify** — pick the metric that does not lie.
4. **Fix one thing** — the smallest change those numbers justify.

Community install (DuckDB **v1.5.5**): `INSTALL quack_flamegraph FROM community;` then `LOAD quack_flamegraph;`

In [10]:
import subprocess
import sys
from pathlib import Path


def repo_root() -> Path:
    here = Path.cwd().resolve()
    for p in [here, *here.parents]:
        if (p / "Cargo.toml").exists() and (p / "scripts" / "extract_perf_demo.py").exists():
            return p
    raise FileNotFoundError(f"repo root not found from cwd={here}")


ROOT = repo_root()
SCRIPT = ROOT / "scripts/extract_perf_demo.py"
OUT = ROOT / "build/perf-demo"
py = ROOT / "configure/venv/bin/python"
exe = str(py if py.exists() else Path(sys.executable))
# Jute SQL kernel is DuckDB 1.5.4; community quack_flamegraph is 1.5.5.
r = subprocess.run([exe, str(SCRIPT)], check=True, capture_output=True, text=True, cwd=ROOT)
print(r.stdout)
if r.stderr:
    print(r.stderr)
print("parquet", sorted(p.name for p in OUT.glob("*.parquet")))

duckdb 1.5.5 samples 25782 folded spur-ade-bench.folded
parquet ['buckets.parquet', 'coverage.parquet', 'edges.parquet', 'exclusive.parquet', 'fix.parquet', 'inflate.parquet', 'overview.parquet', 'pareto.parquet']

parquet ['buckets.parquet', 'coverage.parquet', 'edges.parquet', 'exclusive.parquet', 'fix.parquet', 'inflate.parquet', 'overview.parquet', 'pareto.parquet']

## 1. Same stacks, as a table

`read_folded` turns `test/data/spur-ade-bench.folded` into `frames VARCHAR[]`, `samples BIGINT`. This row is the **inventory**, not a ranking: 25,782 on-CPU samples, 2,289 unique stacks, mean depth 19.1 (max 50).

GGSQL is off here on purpose — a 1-row summary is a table. Charts start when there is a distribution to read.

In [16]:
SELECT samples, stacks, avg_depth, max_depth
FROM read_parquet('../../../build/perf-demo/overview.parquet');

## 2. Unique-stack coverage — do not add the bars

Flamegraph **width is inclusive**. `flamegraph_coverage` counts each unique stack **once**, so a frame's bar is “% of samples whose stack contains this frame.”

**How to read the bar chart:** taller = more stacks pass through that frame. Bars **overlap** (a parse stack is also an `extract_files` stack), so the percentages must not be summed. Near-100% runtime frames (`main`, `lang_start`) are filtered out so the product envelope is visible.

On this live capture the envelope is `build_facts` / `extract_files` (~74%). Tree-sitter parse is 31%. Python re-export resolution (`reexport_source_candidates` → `module_file_matches_suffix`) is ~19% — a Spur path, not C.

In [15]:
SELECT frame, coverage, n_stacks, pct
FROM read_parquet('../../../build/perf-demo/coverage.parquet')
ORDER BY pct DESC;

**Inflate chart (next).** `flamegraph_inclusive` unnests, so a recursive/closure name on the same stack is counted once **per occurrence**. `inflate = inclusive / coverage`. On this capture the only material inflate (≥1.05 at ≥1% coverage) is Lance’s inverted-index builder at **2.0** (7.1% coverage looks like 14% inclusive). Rank by coverage, not inclusive.

In [13]:
SELECT frame, coverage, inclusive, inflate, coverage_pct, inclusive_pct
FROM read_parquet('../../../build/perf-demo/inflate.parquet')
ORDER BY inflate DESC, coverage DESC;

**Pareto of unique stacks.** X is stack rank (fattest first); Y is cumulative % of all samples. A steep early rise means a few fat stacks dominate. Use it to decide whether a fix on one spine (re-export, parse) moves the wall-clock number, or whether time is smeared across thousands of tiny stacks.

In [14]:
SELECT rank, cum_pct, samples, leaf
FROM read_parquet('../../../build/perf-demo/pareto.parquet')
ORDER BY rank;

## 3. Exclusive leaves lie — walk the edge

Hottest **leaf** is `ts_parser_parse` at 9.2% self-time. That is tree-sitter C, not a product function. Exclusive self-time under LTO/ICF also names helpers (`ts_parser__do_all_potential_reductions`, `ts_query__perform_analysis`).

**Exclusive bar chart:** height = % of samples where this frame is the **leaf**. Use it to find on-CPU sit points, then distrust surprising C names until you see the parent.

**Edge heatmap:** fill = % of all samples on that parent → child step. The two hot columns under `extract_files` split the work: parse (~24%) vs `resolve_pending_edges` → Python re-export (~19%). That split is the decision, not the 9% parse leaf.

In [12]:
SELECT leaf, exclusive, pct
FROM read_parquet('../../../build/perf-demo/exclusive.parquet')
ORDER BY pct DESC;

In [17]:
SELECT parent, child, samples, pct
FROM read_parquet('../../../build/perf-demo/edges.parquet')
ORDER BY pct DESC;

In [11]:
SELECT bucket, samples, n_stacks, pct
FROM read_parquet('../../../build/perf-demo/buckets.parquet')
ORDER BY pct DESC;

## 4. One fix the numbers justify

**Bucket bars sum to 100%.** Each unique stack is assigned exactly one label (priority: Python re-export → parse → buckets → other extract → spawn/IO → other). This is the chart to compare magnitudes without double-counting.

| Rank | What the SVG/leaf says | What the SQL says | Action |
|---|---|---|---|
| 1 | Hottest leaf `ts_parser_parse` (9%) | Disjoint parse bucket 31%, but it sits *inside* extract; re-export is a separate **18.7%** bucket | **Cap/cache Python `module_file_matches_suffix` / re-export candidate walk** |
| 2 | `buckets_from_facts` exclusive 2.9% | Disjoint bucket D 6.5% | Re-profile after #1 |
| — | Parse looks huge on the flamegraph | It is the C sit-point of extract, not an independent product bug | Do not start here |

The modeled fix (next chart) drops stacks in the re-export walk: **18.7% removed, 81.3% remaining**. That is a SQL counterfactual, not a patch.

In [18]:
SELECT slice, samples, pct
FROM read_parquet('../../../build/perf-demo/fix.parquet')
ORDER BY samples DESC;

## Decision: attack one thing, measure two

Wall-clock is **6.75s**, almost all on-CPU (4.72 user + 1.36 sys). This is a compute problem, not an off-CPU wait problem.

**Attack now (one change)**

1. **Python re-export candidate walk — 18.7% disjoint.** Edge chain `extract_files` → `resolve_pending_edges` → `reexport_source_candidates` → `module_file_matches_suffix` (~14% of that is `format_inner`). This is Spur code. Cap, cache, or index module-suffix matches so import resolution is not a linear scan + format per candidate. SQL already models **−18.7% samples** if that spine goes away.

**Do not attack yet (measure more)**

2. **Parse-inside-extract — 31% of stacks, 9.2% exclusive `ts_parser_parse`.** This is tree-sitter C sitting *inside* extract, not a separate product function. Before touching the grammar, split:
   - `ts_query_new` (2.2% exclusive) — are queries compiled **per file** instead of once per language?
   - `ts_query__perform_analysis` (5.6%) vs `ts_lex` (2.3%) vs reductions (5.9%) — compile vs scan vs parse.
   A query-cache is a one-line experiment; rewriting parse is not.

3. **Other extract (24.6% bucket)** — `build_facts` leftover after parse + re-export. Need a coverage slice of *this* bucket alone (pending-edge work that is not re-export, markdown, SQL extract). Do not optimize “extract” as a blob.

**Later / after the first re-profile**

4. **`buckets_from_facts` — 6.5% disjoint, 2.9% exclusive.** Real, but 3× smaller than re-export. Re-measure after #1; it may grow or vanish in rank.
5. **`__open` / `posix_spawn` — 2.5–3.6%.** Not the wall. Ignore until on-CPU extract is cut.
6. **Lance inflate 2.0 (7.1% coverage).** Inclusive looks like 14%. Ranking trap, not a fix. Keep using coverage.

**How to read the next chart:** color is the decision (`ATTACK now` / `MEASURE more` / `Later`). Height is the disjoint bucket % (bars *do* sum to ~100%). Attack the orange 18.7% first; the 31% parse bar is the thing to *instrument*, not rewrite.

In [19]:
SELECT CASE bucket
         WHEN 'A_python_reexport' THEN 'ATTACK now'
         WHEN 'C_extract_parse' THEN 'MEASURE more'
         WHEN 'E_extract_other' THEN 'MEASURE more'
         WHEN 'D_buckets' THEN 'Later'
         WHEN 'F_spawn_io' THEN 'Later'
         ELSE 'Ignore v1'
       END AS action,
       bucket AS item,
       samples,
       pct
FROM read_parquet('../../../build/perf-demo/buckets.parquet')
ORDER BY pct DESC;

## 5. Re-profile

After the re-export cap lands, capture a new folded file (`samply record --rate 4000`) and re-run this notebook. The next bottleneck should be parse-inside-extract (~31% bucket) or `buckets_from_facts` (~6.5%) — **measured**, not guessed.

```sql
INSTALL quack_flamegraph FROM community;
LOAD quack_flamegraph;
SELECT * FROM flamegraph_coverage('test/data/spur-ade-bench.folded')
ORDER BY coverage DESC LIMIT 12;
```